language: node_js
node_js:
  - 12
  - 14
service:
  - postgresql
  - redis-server
before_script:
  - npm install
  - psql -c "CREATE DATABASE test_db;" -U postgres
  - psql -c "CREATE USER test WITH PASSWORD 'test';" -U postgres
script:
  - npm test
